baseURL = "/"
title = "Home"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Mellit BV" # title for frontpage, may include image
copyright = "Melvin Hulsmans"
description = 'We build your solutions'
#startbuttonText = "Activate"
#startbuttonLink = "#"git
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[[params.menu.main]]
url = '/cv/'
title = "Curriculum Vitae"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

#[params.one]
#enable = true
#title = 'Committed to creating a lasting solution'
#body = '''
#Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend
#fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
#'''
#
#[[params.one.icon]]
#icon = "fa-gem"
#style = "1"
#label = "Lorem"
#
#[[params.one.icon]]
#icon = "fa-heart"
#style = "2"
#label = "Ipsum"
#
#[[params.one.icon]]
#icon = "solid fa-code"
#style = "3"
#label = "Dolor"

[params.two]
enable = true

[params.three]
enable = true
title = 'Solving your problems with the right mindset'
body = '''
There is a difference between doing a job and doing a good job.
At Mellit BV we try to keep the following in mind when helping you achieve your goals.
'''

[[params.three.feature]]
icon = "solid fa-code"
title = "Clean code"
body = "Investing time now prevents losing time in the future. The same goes for maintaining code."

[[params.three.feature]]
icon = "solid fa-magnifying-glass"
title = "Being critical"
body = "Critical reflection and providing constructive feedback is important to keep the code quality optimal and make everyone improve."

[[params.three.feature]]
icon = "fa-heart"
title = "Contributing to a healthy team atmophere"
body = "Even the most experienced developer will not be able to win from a well-oiled team. Hence teamwork is a vital part of building applications."

[[params.three.feature]]
icon = "fa-flag"
title = "Setting goals"
body = "IT is always evolving, hence we need to do the same. Only by looking ahead can we prevent getting stuck."

[[params.three.feature]]
icon = "solid fa-bug"
title = "Problem solving"
body = "Making mistakes is human, however not learning from them is lazyness. Improving bug detection and knowledge sharing can save a lot of time and frustration."

[[params.three.feature]]
icon = "fa-lemon"
title = "Positive mindset"
body = "You're still reading these? This is all just padding. Fine something something lemonade, trying to make the best of a bad day does wonders for motivation."


[params.cta]
enable = true
title = "What can we mean for you?"
body = ""

[[params.cta.link]]
href = "cv"
text = "Our talents"
special = true

[[params.cta.link]]
href = "posts"
text = "Blogs"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Feel free to leave a message"
phone = ""
address = ""
email = "contact.site@mellit.dev"
subject = "New Submission from your website."
formspree_form_id = "example_invalid"

[params.social]
#twitter = ""
#mastodon = ""
github = "MelvinHuls"
#facebook = ""
#youtube = ""
#instagram = ""
#dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"